const SUB_PARAMS_OF_AREAINFO = '&MobileOS=ETC&MobileApp=AppTesting&_type=json'
const API_KEY_OF_AREAINFO =
  'ServiceKey=oYDSqwkb%2BcLyJV%2FdX6UALRo40Q9EEkHKnC%2F62cii25T%2B%2BJY0k2ZMhSlpLml81eqX8q9IgS9HVRqIQugoCUJqtQ%3D%3D'
const BASE_ROUTE_OF_AREAINFO =
  'http://api.visitkorea.or.kr/openapi/service/rest/KorService/areaCode?'

const API_ENDPOINT_OF_DEVCOURSE = 'http://13.209.30.200:5000/'
const API_ENDPOINT_OF_AREAINFO =
  BASE_ROUTE_OF_AREAINFO + API_KEY_OF_AREAINFO + SUB_PARAMS_OF_AREAINFO

export { API_ENDPOINT_OF_DEVCOURSE, API_ENDPOINT_OF_AREAINFO }
